/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://knt4ief5d5hbzee7ngnwd7ui6a.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-e37oxructfde7pipxpmuezcqky",
    "aws_cognito_identity_pool_id": "us-east-1:411d4a1c-e11f-4a33-bd3c-b8f9c0b82c3c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ujCLc5f7e",
    "aws_user_pools_web_client_id": "6smqd7k8mtjatu44eq9l47s871",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "creatorkitchen202119-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
